FROM mongo:7
RUN apt-get update && apt-get install -y jq
COPY docker/mongo-init/ /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/startup.sh
RUN chmod +x /docker-entrypoint-initdb.d/data.jsonl


